KafkaServer {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  keyTab="/kerby/keytabs/kafka-broker1.keytab"
  principal="kafka/broker1.example.com@EXAMPLE.COM";
};

Client {
  com.sun.security.auth.module.Krb5LoginModule required
  useKeyTab=true
  storeKey=true
  keyTab="/kerby/keytabs/kafka-broker1.keytab"
  principal="kafka/broker1.example.com@EXAMPLE.COM";
};
