clusters=primary,standby
primary.bootstrap.servers=broker1.example.com:9092
standby.bootstrap.servers=broker2.example.com:9093

primary.security.protocol=SASL_PLAINTEXT
primary.sasl.mechanism=GSSAPI
primary.sasl.kerberos.service.name=kafka
primary.sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/kerby/keytabs/mm2.keytab" principal="mm2/mm2.example.com@EXAMPLE.COM";

standby.security.protocol=SASL_PLAINTEXT
standby.sasl.mechanism=GSSAPI
standby.sasl.kerberos.service.name=kafka
standby.sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/kerby/keytabs/mm2.keytab" principal="mm2/mm2.example.com@EXAMPLE.COM";

primary->standby.enabled=true
standby->primary.enabled=false
primary->standby.topics=kerberos.messages|primary.orders|primary.payments|primary.audit
primary->standby.groups=.*
replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy

replication.factor=1
checkpoints.topic.replication.factor=1
heartbeats.topic.replication.factor=1
offset-syncs.topic.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
config.storage.replication.factor=1

sync.topic.acls.enabled=false
sync.topic.configs.enabled=true
refresh.topics.enabled=true
refresh.topics.interval.seconds=10
emit.heartbeats.enabled=true
emit.checkpoints.enabled=true
tasks.max=2
